version: "3.3"

services:
    datacaker:
        build: ./mongodb
        volumes: 
            - db:/DataCaker
        expose:
            - 27017

    gunicorn:
        build: ./mooncaker
        ports:
            - 80:80
            - 443:443
        depends_on:
            - datacaker

volumes:
    db:

